### ISSUE TITLE
Get user profile picture from server

### ISSUE THREAD

**Issue by Shimitan** [AOsnes/p2#116]

**Comment by Sigurd00** [comment]
Der er en del(?) infrastruktur der skal opsættes for at dette kan lade sig gøre. Har ikke lige kigget på det men det kan nok nemt lade sig gøre. Vi skal nok:

Gemme billeder på DB,
Spørge om det rigtige billede på frontend (brug ID fra den der er logget ind)
query DB på serveren og svare når der kommer et HTTP request på fx /profilepicture

**Comment by Sigurd00** [comment]
ikke prio
