### ISSUE TITLE
Lav view controller component

### ISSUE THREAD

**Issue by Sigurd00** [AOsnes/p2#134]
Der skal laves et component som bestemmer om der skal være 5 day view eller 1 day view.

Den kan bare bestemme hvilket component det bliver rendered ud fra dens state. Som default vil den have 1 day view i sin state, og slideren vil så bare toggle frem og tilbage mellem 1 og 5 dag view. Det kan være en boolean.

Hvilket component der bliver renderet kan bestemmes med en conditional statement:

`dayView ? <OneDayView/> : <FiveDayView/>`

**Comment by VictorDore** [comment]
#149
