### ISSUE TITLE
Logout dropdown layeret bag skema

### ISSUE THREAD

**Issue by Sigurd00** [AOsnes/p2#135]
https://www.dropbox.com/s/2b6c0yjkff82vj0/2021-05-04_10-59-58.mp4?dl=0

Det virkede ikke for mig at ændre z-index

**Comment by Shimitan** [comment]
Tror det er pga. schedule.component bliver rendered efter header.component, hvilket gør at header.component altid vil være under schedule.component.

**Comment by AndreasAhlbeck** [comment]
https://www.freecodecamp.org/news/4-reasons-your-z-index-isnt-working-and-how-to-fix-it-coder-coder-6bc05f103e6c/ Måske det har noget med punkt 3. her at gøre da vi har opacity og transform på logout button :/
