### ISSUE TITLE
Begræns timeIndicator til kun at blive renderet indenfor skemaet

### ISSUE THREAD

**Issue by VictorDore** [AOsnes/p2#158]
Pt er timeIndicatoren ikke begrænset til kun at blive renderet indenfor schedule og ender derfor med at bevæge sig udenfor skemaet, når klokken er mindre end 8 eller mere end 16.  Se billede. Dette kan formentlig fixes ved kun at render timeIndicatoren, hvis currentTime er indenfor skemaets rammer (currentTime >= 8 && currentTime <= 16)
![image](https://user-images.githubusercontent.com/74188341/117471153-d8d84600-af57-11eb-9ca7-bc4d76a5206d.png)

**Comment by Sigurd00** [comment]
#159 closes this issue
