### ISSUE TITLE
Tests af server

### ISSUE THREAD

**Issue by Sigurd00** [AOsnes/p2#51]
https://trello.com/c/Kfnn6XgR/5-unit-testing

Der er en række funktioner på server siden som kan blive testet nu hvor jest er sat op til at virke på /server directory

- [ ] authenticate
- [ ] getSchedule
- [ ] createLesson
- [ ] updateLesson

Derudover er der en række endpoints som også kan blive testet

- [ ] POST /login
- [ ] POST /classes
- [ ] GET /classes
Samt mange flere meget snart...

**Comment by VictorDore** [comment]
Afventer umiddelbart at alt andet er på plads - kræver at der laves en mock af serveren
