### ISSUE TITLE
CSS for log out button

### ISSUE THREAD

**Issue by Shimitan** [AOsnes/p2#93]
From this:
![image](https://user-images.githubusercontent.com/43805784/115397866-d56a5e00-a1e6-11eb-9b51-26a7d51c7cea.png)
To this:
![image](https://user-images.githubusercontent.com/43805784/115398025-ffbc1b80-a1e6-11eb-97cc-32b18b35cd4e.png)

**Comment by VictorDore** [comment]
#112 
css for dropdown menu added - dropdown triangle css still missing though

**Comment by Sigurd00** [comment]
Det ligner ikke præcis, men det er godt nok. Specielt fordi vi ikke vil implementere de features der står i menuen
![billede](https://user-images.githubusercontent.com/24461644/116555049-3804dd80-a8fc-11eb-9f15-8e8e4421ad25.png)
